---
- name: Configure OPS445 Linux VM
  hosts: vmlab
  become: yes
  vars:
    seneca_id: dnthakar
  tasks:
    - name: Update Apache httpd to latest version
      yum:
        name: httpd
        state: latest

    - name: Install EPEL repo if not installed
      yum:
        name: epel-release
        state: present

    - name: Remove tree package if installed
      yum:
        name: tree
        state: absent

    - name: Set hostname to Seneca ID
      hostname:
        name: "{{ seneca_id }}"

    - name: Create new user with sudo access
      user:
        name: "{{ seneca_id }}"
        state: present
        groups: wheel
        append: yes
        create_home: yes
        shell: /bin/bash

    - name: Set authorized key for new user to allow passwordless SSH
      authorized_key:
        user: "{{ seneca_id }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Create ops445 lab directories
      file:
        path: "/home/{{ seneca_id }}/ops445/lab{{ item }}"
        state: directory
        owner: "{{ seneca_id }}"
        group: "{{ seneca_id }}"
        mode: '0755'
      loop: "{{ range(1, 9) | list }}"

